### PR TITLE
Refactored handlers: structs in packages

### LINKED ISSUE #37: Refactor handlers
We should make handlers cleaner and make objects of them, so they can call different functions on the same members and can store config data and a state for easier implementation.

### PR DESCRIPTION
**Pull request by DenBeke**
Moved from single functions to different structs in different packages,
so they can contain context and can be loaded in a cleaner way.

The mailqueue is currently disabled as it must be implemented into the HandlerMechanism in the future

Fixes #37

### CODE REVIEW

**Comment by DenBeke** [comment]
@trtstm can you try my `handlers` branch locally? Because Travis doesn't like me...

**Comment by DenBeke** [comment]
I think this is ready for now, @trtstm...  
If you merge I'll look into better config. #36

**Comment by trtstm** [comment]
Why not let handlermechanism implement the handler interface?

**Comment by DenBeke** [comment]
> Why not let handlermechanism implement the handler interface?

I could do that, @trtstm. But it must especially implement the `mta.Handler` interface, which has a `HandleMail` function instead of `Handle` function. But I'll do both...

**Comment by trtstm** [comment]
Can't we then just have 1 interface? They implement the same methods anyway.

**Comment by DenBeke** [comment]
Sure, but then I'll have to update the MTA package...
If you merge this, I'll rename the functions in MTA package and this package for more convenient naming.

**Pull request merged**
