### PR TITLE
Stash: handling mail

### PR DESCRIPTION
**Pull request by DenBeke**
Working on mail handling. We need to add a mail handler function to the config struct.
But we need to give it some more information, which the mail handler will need. Think about ip's for e.g. spam detection. 

My first thoughts:

* from
* to
* data
* sender IP
* flag denoting wether TLS was used?

What am I forgetting, @trtstm ?

Don't merge this, I'll work on it, but here we can discuss it.

### CODE REVIEW

**Comment by trtstm** [comment]
Add more info the the state struct, and give that to the handler? The state currently has the from,to,mail data.
I would just pass the handler to the constructor of the mta. Like the http.ListenAndServe.

**Comment by DenBeke** [comment]
> Add more info the the state struct, and give that to the handler? The state currently has the from,to,mail data.

That's what I thought too...

**Comment by DenBeke** [comment]
Incoming mails are now stored in with maildir :)

**Comment by DenBeke** [comment]
You can view mails in the terminal with `mutt`:

    $ mutt -f maildir/

schermafbeelding 2015-10-20 om 22 10 56

**Pull request merged**
