### PR TITLE
Better logging and wrapper around 'log'

### PR DESCRIPTION
**Pull request by DenBeke**
Created a wrapper around log, and used it to change to [Logrus](https://github.com/Sirupsen/logrus).

This pull request is no more than changing the logger. So no extra log info, levels, details, ... were added. I will update this PR if I worked more on it. (You can also push to this branch...)

schermafbeelding 2015-10-30 om 22 04 36

### CODE REVIEW

**Comment by DenBeke** [comment]
I've added some nice levels...

schermafbeelding 2015-10-31 om 16 45 35

I also added a `SessionId` and the `Ip` to the state.

**Comment by trtstm** [comment]
sure

**Comment by DenBeke** [comment]
Ready to merge... Except if you want to do those changes before merging...

> I think adding a method GetIp() to the smtp.Protocol is the cleanest way.

**Comment by trtstm** [comment]
That can wait :)

**Comment by DenBeke** [comment]
> That can wait :)

Make an issue for it :p

**Pull request merged**
